# Generated by Django 4.2.10 on 2024-03-19 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_team',
            name='user',
        ),
        migrations.AddField(
            model_name='project_team',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
