# Generated by Django 4.2.10 on 2024-03-21 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Progress', 'Progress'), ('complete', 'complete')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='taksid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.task'),
        ),
    ]
