# Generated by Django 4.2.10 on 2024-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_image',
            name='img',
            field=models.ImageField(upload_to='Profile_Image'),
        ),
    ]
